### ISSUE TITLE
C# Application

### ISSUE THREAD

**Issue by Nicholas27** [KurochenkoEugene/CarsStudy#10]
Приложение должно содержать поля 
-  для ввода расширения пример (.sql, .txt)
- для выбора пути поиска ( https://msdn.microsoft.com/ru-ru/library/system.windows.forms.openfiledialog(v=vs.110).aspx)
-  поле для вывода имен найденных файлов (каждый файл с новой строчки)

И кнопку начать поиск, очистить поля

**Comment by KurochenkoEugene** [comment]
fixed. See: https://github.com/KurochenkoEugene/CS

**Comment by Nicholas27** [comment]
1) Please use naming convension
2) Add validation if Extension and TextField are empty
