### ISSUE TITLE
Create new c# application

### ISSUE THREAD

**Issue by Nicholas27** [KurochenkoEugene/CarsStudy#14]
You need create c# application with grid that contains some data (for example users).
Add to topbar Add button and edit/delete button to item grid. All data from grid must contain to mssql or sqllite database.

**Comment by Nicholas27** [comment]
Please add button for grid "Export to Word"

**Comment by KurochenkoEugene** [comment]
Fixed. https://www.dropbox.com/s/skvmi9zvbnpmltx/SystemControlCars_v2.rar?dl=0
