### ISSUE TITLE
Login page

### ISSUE THREAD

**Issue by Nicholas27** [KurochenkoEugene/CarsStudy#2]
1) Add padding  http://prntscr.com/c4a8lr
2) Button Sign on the center http://prntscr.com/c4a8t9
3) Login Page on the center http://prntscr.com/c4a91a
4) Set maxLength is 50 characters for Your login and Your password

**Comment by KurochenkoEugene** [comment]
1 - fixed
2 - fixed
3 - fixed
4 - fixed
